name: ephesusframework
description: A backend framework for Dart.
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: 1.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
